### ISSUE TITLE
Cannot build doc-jars with -Xfatal-warnings

### ISSUE THREAD

**Issue by olix0r** [twitter/scrooge#220]
We build our projects with the `-Xfatal-warnings` scalac option to enforce good hygiene.  Scrooge-generated enum types cause compilation failures, do to a scaldoc error:

```
[error] .../thriftscala/MyEnumKind.scala:34: Could not find any member to link for "NoSuchElementException".
[error]   /**
[error]   ^
```

The failing generated comment is:

```
/**
 * Find the enum by its integer value, as defined in the Thrift IDL.
 * @throws NoSuchElementException if the value is not found.
 */
```

I'm not exactly sure what the proper solution, but in the worst case it seems preferable to omit the @throws clause if it cannot build without warnings.

**Comment by olix0r** [comment]
btw, I'm happy to submit a PR that just removes the @throws docstring; though I'm curious if there's a better way to do this.

**Comment by travisbrown** [comment]
The class name should be fully qualified, since `java.util` isn't in scope in Scala by default, but even then I don't think this is going to work, since Scaladoc doesn't know how to link to the Java standard library's docs.

In general linking to Javadocs is hugely annoying. I've used [these answers](http://stackoverflow.com/q/16934488/334519) before, but I really wish someone would package all that crap up into a convenient SBT plugin (it's just below my threshold for caring enough to do it myself).

**Comment by kevinoliver** [comment]
i don't think the scaladoc is buying us too much. i _think_ scala relies on `@throws` annotations for java devs, but i'm not sure tbh.

**Comment by mosesn** [comment]
:+1: to removing the `@throws` docstring.

**Comment by mosesn** [comment]
@olix0r are you still interested in making that PR?

**Comment by chrisbenincasa** [comment]
I've opened a PR that fixes this behavior: https://github.com/twitter/scrooge/pull/267

**Comment by mosesn** [comment]
thanks @chrisbenincasa!  this has been fixed here: https://github.com/twitter/scrooge/commit/34989e2395f71934bc1a552299f0e078d8a71c9e
