### ISSUE TITLE
sbt-scrooge-plugin doesn't include generated sources in packageSrc

### ISSUE THREAD

**Issue by chessman** [twitter/scrooge#239]
sbt-scrooge-plugin doesn't include generated sources in packageSrc.

### Expected behavior

sbt-scrooge-plugin includes generated sources from `scroogeThriftOutputFolder` in sources jar.

### Actual behavior

sbt-scrooge-plugin generates empty sources jar.

### Steps to reproduce the behavior

build.sbt
``` scala
import sbt.Keys.{artifactPath, libraryDependencies, mainClass, managedClasspath, name, organization, packageBin, resolvers, version}

lazy val projectName = "scrooge-bug"
lazy val projectVersion = "0.0.1"

organization := "com.example"

scalaVersion := "2.11.8"

version := s"$projectVersion-SNAPSHOT"

name := s"$projectName"

libraryDependencies ++= Seq(
  "org.apache.thrift" % "libthrift" % "0.9.3",
  "com.twitter" %% "scrooge-core" % "4.5.0",
  "com.twitter" %% "scrooge-linter" % "4.5.0",
  "com.twitter" %% "finagle-thrift" % "6.33.0"
)
```

project/plugins.sbt
``` scala
addSbtPlugin("com.twitter" %% "scrooge-sbt-plugin" % "4.5.0")
```

src/main/thrift/test.thrift
``` thrift
namespace js test
#@namespace scala com.example.thrift.test

struct TestStruct {
    1: required i64 abc
    2: required string cba
}
```

1. sbt compile
2. sbt packageSrc
3. target/scala-2.11/scrooge-bug_2.11-0.0.1-SNAPSHOT-sources.jar doesn't include generated sources (target/scala-2.11/src_managed/main/com/example/thrift/test/TestStruct.scala).

**Comment by mosesn** [comment]
@chessman hmm, this is really interesting.  thanks for the bug report!  Is this something we can change in the scrooge sbt plugin, or do you have to do it on your side?

It looks like there's an explanation [here][0].

so it looks like we would do something like:

```scala
mappings in (Compile, packageSrc) <+= baseDirectory.map { base =>
   (base / "target" / "scala-2.11" / "src_managed" ) -> "src_managed"
}
```

but would it work if we added it to [projectSettings][1]?

If it turns out we can fix it in scrooge, would you be interested in making a PR?

[0]: http://www.scala-sbt.org/0.12.1/docs/Howto/package.html#contents
[1]: https://github.com/twitter/scrooge/blob/develop/scrooge-sbt-plugin/src/main/scala/com/twitter/ScroogeSBT.scala#L288-L291

**Comment by chessman** [comment]
Ok, I will try to figure out and do a PR.

**Comment by mosesn** [comment]
@chessman fixed this here: https://github.com/twitter/scrooge/commit/572609efc41575590a8790b13241b374f26e9c9e 😎
